"""Attempt ingestion: validates against a problem's declared skills, updates
mastery, and answers what a student currently knows for a course."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from sqlmodel import Session, select

from app.database import CourseRepository
from app.models.attempt import Attempt
from app.models.skill import Skill
from app.models.skill_state import SkillState
from app.schemas.learning import (
    AttemptCreate,
    AttemptResult,
    SkillOverviewOut,
    SkillsOverviewResponse,
    SkillStateOut,
    StudentModelResponse,
)
from app.services import selection
from app.services.mastery import (
    MASTERY_CEIL,
    MASTERY_FLOOR,
    clamp,
    confidence,
    prereq_delta,
    score_attempt,
    update_mastery,
)

logger = logging.getLogger(__name__)

# How long a generated skill is flagged "recent" on the dashboard after
# creation -- long enough to notice it appear mid-session, short enough that
# the flag isn't still on from a run days ago.
RECENT_SKILL_WINDOW = timedelta(minutes=15)


class UnknownSkillError(ValueError):
    """An attempt declared expected_skills not present in the course taxonomy."""


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _update_streak(streak: int, correct: bool) -> int:
    if correct:
        return streak + 1 if streak >= 0 else 1
    return streak - 1 if streak <= 0 else -1


def _get_or_create_skill_state(
    session: Session, student_id: str, course_id: str, skill_id: str, *, practised: bool
) -> SkillState:
    """Fetch a skill's state, creating it at the cold-start default if absent.

    `practised=False` leaves last_seen null. Prerequisite bleed creates states
    for skills the student never attempted; stamping those with "now" would
    reset their staleness and restart their decay clock, so bleed would read
    as revision.
    """
    state = session.get(SkillState, (student_id, skill_id))
    if state is None:
        state = SkillState(
            student_id=student_id,
            course_id=course_id,
            skill_id=skill_id,
            mastery=selection.DEFAULT_MASTERY,
            last_seen=_utcnow() if practised else None,
        )
        session.add(state)
        session.flush()
    return state


def _existing_attempt(session: Session, student_id: str, problem_id: str) -> Attempt | None:
    return session.exec(
        select(Attempt).where(
            Attempt.student_id == student_id, Attempt.problem_id == problem_id
        )
    ).first()


def _resolve_skills(
    payload: AttemptCreate, repository: CourseRepository | None
) -> list[str]:
    """Which skills this attempt exercised.

    When the problem was generated by us, its problem_skills rows are the
    source of truth and the client's expected_skills is only a hint we
    cross-check -- a client cannot attribute an attempt to a skill it names.
    Problems with no row (legacy, or externally authored) fall back to the
    client's list, and that fallback is logged rather than silent.
    """
    if repository is None:
        return payload.expected_skills

    server_skills = repository.get_problem_skills(payload.problem_id)
    if not server_skills:
        logger.info(
            "problem %s has no problem_skills row; trusting client expected_skills %s",
            payload.problem_id,
            payload.expected_skills,
        )
        return payload.expected_skills

    if set(server_skills) != set(payload.expected_skills):
        logger.warning(
            "problem %s: overriding client expected_skills %s with server-side %s",
            payload.problem_id,
            payload.expected_skills,
            server_skills,
        )
    return server_skills


def record_attempt(
    session: Session,
    course_id: str,
    payload: AttemptCreate,
    repository: CourseRepository | None = None,
) -> AttemptResult:
    # One problem, one attempt. The whiteboard posts on every "mark", so
    # repeats are expected traffic -- they are answered with the original
    # attempt rather than counted again, which would let ten marks on one
    # correct canvas saturate mastery.
    existing = _existing_attempt(session, payload.student_id, payload.problem_id)
    if existing is not None:
        logger.info(
            "attempt for problem %s by %s already recorded; returning it unchanged",
            payload.problem_id,
            payload.student_id,
        )
        return AttemptResult(
            attempt_id=existing.id,
            updated_skills={
                skill_id: state.mastery
                for skill_id in existing.expected_skills
                if (state := session.get(SkillState, (payload.student_id, skill_id)))
            },
        )

    expected_skills = _resolve_skills(payload, repository)

    skills = session.exec(
        select(Skill).where(Skill.course_id == course_id, Skill.id.in_(expected_skills))
    ).all()
    skills_by_id = {s.id: s for s in skills}
    missing = set(expected_skills) - set(skills_by_id)
    if missing:
        raise UnknownSkillError(
            f"expected_skills not found in course '{course_id}': {sorted(missing)}"
        )

    score = score_attempt(
        correct=payload.correct, hints_used=payload.hints_used, partial=payload.partial
    )

    updated_skills: dict[str, float] = {}
    prereq_deltas: dict[str, float] = {}

    for skill_id in expected_skills:
        state = _get_or_create_skill_state(
            session, payload.student_id, course_id, skill_id, practised=True
        )
        new_mastery = update_mastery(state.mastery, score, payload.difficulty, state.attempts)
        delta = new_mastery - state.mastery

        state.mastery = new_mastery
        state.attempts += 1
        if payload.correct and payload.hints_used == 0:
            state.correct_unassisted += 1
        state.streak = _update_streak(state.streak, payload.correct)
        state.last_seen = _utcnow()
        session.add(state)

        updated_skills[skill_id] = new_mastery

        for prereq_id in skills_by_id[skill_id].prereqs:
            prereq_deltas[prereq_id] = prereq_deltas.get(prereq_id, 0.0) + prereq_delta(delta)

    # Bleed onto direct prerequisites only (one level), after the primary
    # skills are updated so a skill that is both a target and a prerequisite
    # of another target isn't double-counted against a stale mastery.
    for prereq_id, bleed in prereq_deltas.items():
        if prereq_id in updated_skills:
            continue
        prereq_state = _get_or_create_skill_state(
            session, payload.student_id, course_id, prereq_id, practised=False
        )
        prereq_state.mastery = clamp(prereq_state.mastery + bleed, MASTERY_FLOOR, MASTERY_CEIL)
        session.add(prereq_state)

    attempt = Attempt(
        student_id=payload.student_id,
        course_id=course_id,
        session_id=payload.session_id,
        problem_id=payload.problem_id,
        expected_skills=expected_skills,
        difficulty=payload.difficulty,
        correct=payload.correct,
        partial=payload.partial,
        hints_used=payload.hints_used,
        total_time_ms=payload.total_time_ms,
    )
    session.add(attempt)
    session.commit()

    return AttemptResult(attempt_id=attempt.id, updated_skills=updated_skills)


def get_student_model(session: Session, course_id: str, student_id: str) -> StudentModelResponse:
    """Current decayed mastery for every skill this student has attempted."""
    skills = session.exec(select(Skill).where(Skill.course_id == course_id)).all()
    now = _utcnow()
    states = session.exec(
        select(SkillState).where(
            SkillState.student_id == student_id,
            SkillState.skill_id.in_([s.id for s in skills]),
        )
    ).all()
    state_by_id = {state.skill_id: state for state in states}

    out = []
    for skill in skills:
        state = state_by_id.get(skill.id)
        if state is None:
            continue
        progress = selection.decayed_progress(state, now)
        out.append(
            SkillStateOut(
                skill_id=skill.id,
                skill_name=skill.name,
                mastery=progress.mastery,
                confidence=confidence(progress.attempts),
                attempts=progress.attempts,
            )
        )

    return StudentModelResponse(student_id=student_id, course_id=course_id, skills=out)


def get_skills_overview(
    session: Session, course_id: str, student_id: str
) -> SkillsOverviewResponse:
    """Every skill with this student's decayed progress and unlock state.

    Read-only dashboard view. Untouched skills appear at the cold-start
    default rather than being omitted.
    """
    skills = list(session.exec(select(Skill).where(Skill.course_id == course_id)).all())
    now = _utcnow()
    progress = selection.progress_by_skill(session, skills, student_id, now)
    attempted = {
        state.skill_id
        for state in session.exec(
            select(SkillState).where(
                SkillState.student_id == student_id,
                SkillState.skill_id.in_([s.id for s in skills]),
            )
        ).all()
    }

    out: list[SkillOverviewOut] = []
    for skill in skills:
        p = progress[skill.id]
        created_at = skill.created_at
        if created_at.tzinfo is None:
            created_at = created_at.replace(tzinfo=timezone.utc)

        out.append(
            SkillOverviewOut(
                skill_id=skill.id,
                skill_name=skill.name,
                description=skill.description,
                difficulty_band=skill.difficulty_band,
                prereqs=list(skill.prereqs),
                keywords=list(skill.keywords),
                question_forms=list(skill.question_forms),
                origin=skill.origin,
                created_at=created_at,
                is_recent=(now - created_at) <= RECENT_SKILL_WINDOW,
                mastery=p.mastery,
                confidence=confidence(p.attempts),
                attempts=p.attempts,
                unlocked=selection.is_unlocked(skill, progress),
                has_state=skill.id in attempted,
            )
        )

    spec = None
    try:
        spec = selection.select_next(session, course_id, student_id)
    except Exception:  # a read-only view must never fail because selection did
        logger.exception("select_next failed while building skills overview")

    return SkillsOverviewResponse(
        student_id=student_id,
        course_id=course_id,
        skills=out,
        next_skill_id=spec.skill_id if spec is not None else None,
    )
