"""Attempt ingestion: validates against a problem's declared skills, updates
the per-topic rolling window, and answers the dashboard's overview query."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from sqlmodel import Session, select

from app.models.attempt import Attempt
from app.models.skill import Skill
from app.models.skill_state import SkillState
from app.schemas.learning import (
    AttemptCreate,
    AttemptResult,
    SkillOverviewOut,
    SkillsOverviewResponse,
)
from app.services import attribution
from app.services.accuracy import accuracy, has_signal, push_outcome, score_attempt

logger = logging.getLogger(__name__)

# How long a newly-appended topic is flagged "recent" on the dashboard --
# long enough to notice it appear mid-session, short enough that the flag
# isn't still on from a run days ago.
RECENT_SKILL_WINDOW = timedelta(minutes=15)


class UnknownSkillError(ValueError):
    """An attempt declared expected_skills not present in the course taxonomy."""


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _get_or_create_skill_state(
    session: Session, student_id: str, course_id: str, skill_id: str
) -> SkillState:
    state = session.get(SkillState, (student_id, skill_id))
    if state is None:
        state = SkillState(student_id=student_id, course_id=course_id, skill_id=skill_id)
        session.add(state)
        session.flush()
    return state


def _existing_attempt(session: Session, student_id: str, problem_id: str) -> Attempt | None:
    return session.exec(
        select(Attempt).where(
            Attempt.student_id == student_id, Attempt.problem_id == problem_id
        )
    ).first()


def _resolve_skills(session: Session, payload: AttemptCreate) -> list[str]:
    """Which skills this attempt exercised.

    When the problem was generated by us, its ProblemSkill rows are the
    source of truth and the client's expected_skills is only a hint we
    cross-check -- a client cannot attribute an attempt to a skill it names.
    Problems with no row (legacy, or externally authored) fall back to the
    client's list, and that fallback is logged rather than silent.
    """
    server_skills = attribution.get_problem_skills(session, payload.problem_id)
    if not server_skills:
        logger.info(
            "problem %s has no problem_skills row; trusting client expected_skills %s",
            payload.problem_id,
            payload.expected_skills,
        )
        return payload.expected_skills

    if set(server_skills) != set(payload.expected_skills):
        logger.warning(
            "problem %s: overriding client expected_skills %s with server-side %s",
            payload.problem_id,
            payload.expected_skills,
            server_skills,
        )
    return server_skills


def record_attempt(
    session: Session, course_id: str, payload: AttemptCreate
) -> AttemptResult:
    # One problem, one attempt. The whiteboard posts on every "mark", so
    # repeats are expected traffic -- they are answered with the original
    # attempt rather than counted again.
    existing = _existing_attempt(session, payload.student_id, payload.problem_id)
    if existing is not None:
        logger.info(
            "attempt for problem %s by %s already recorded; returning it unchanged",
            payload.problem_id,
            payload.student_id,
        )
        return AttemptResult(
            attempt_id=existing.id,
            updated_skills={
                skill_id: accuracy(state.recent_outcomes) or 0.0
                for skill_id in existing.expected_skills
                if (state := session.get(SkillState, (payload.student_id, skill_id)))
            },
        )

    expected_skills = _resolve_skills(session, payload)

    skills = session.exec(
        select(Skill).where(Skill.course_id == course_id, Skill.id.in_(expected_skills))
    ).all()
    found = {s.id for s in skills}
    missing = set(expected_skills) - found
    if missing:
        raise UnknownSkillError(
            f"expected_skills not found in course '{course_id}': {sorted(missing)}"
        )

    score = score_attempt(
        correct=payload.correct, hints_used=payload.hints_used, partial=payload.partial
    )

    updated_skills: dict[str, float] = {}
    for skill_id in expected_skills:
        state = _get_or_create_skill_state(session, payload.student_id, course_id, skill_id)
        state.recent_outcomes = push_outcome(state.recent_outcomes, score)
        state.attempts += 1
        if payload.hints_used > 0:
            state.hints_used += 1
        state.last_seen = _utcnow()
        session.add(state)
        updated_skills[skill_id] = accuracy(state.recent_outcomes) or 0.0

    attempt = Attempt(
        student_id=payload.student_id,
        course_id=course_id,
        session_id=payload.session_id,
        problem_id=payload.problem_id,
        expected_skills=expected_skills,
        difficulty=payload.difficulty,
        correct=payload.correct,
        partial=payload.partial,
        hints_used=payload.hints_used,
        total_time_ms=payload.total_time_ms,
    )
    session.add(attempt)
    session.commit()

    return AttemptResult(attempt_id=attempt.id, updated_skills=updated_skills)


def get_skills_overview(
    session: Session, course_id: str, student_id: str
) -> SkillsOverviewResponse:
    """Every topic in the course with this student's attempt history.

    Dashboard-only: the product surface never asks "what does this student
    know", because it never shows the student a per-topic readout.
    """
    skills = session.exec(select(Skill).where(Skill.course_id == course_id)).all()
    states = session.exec(
        select(SkillState).where(
            SkillState.student_id == student_id,
            SkillState.skill_id.in_([s.id for s in skills]),
        )
    ).all()
    state_by_id = {state.skill_id: state for state in states}
    now = _utcnow()

    out: list[SkillOverviewOut] = []
    for skill in skills:
        state = state_by_id.get(skill.id)
        created_at = skill.created_at
        if created_at.tzinfo is None:
            created_at = created_at.replace(tzinfo=timezone.utc)

        out.append(
            SkillOverviewOut(
                skill_id=skill.id,
                skill_name=skill.name,
                description=skill.description,
                difficulty_band=skill.difficulty_band,
                keywords=list(skill.keywords),
                question_forms=list(skill.question_forms),
                origin=skill.origin,
                created_at=created_at,
                is_recent=(now - created_at) <= RECENT_SKILL_WINDOW,
                accuracy=accuracy(state.recent_outcomes) if state else None,
                attempts=state.attempts if state else 0,
                has_signal=has_signal(state.attempts) if state else False,
            )
        )

    return SkillsOverviewResponse(student_id=student_id, course_id=course_id, skills=out)
