"""Attempt ingestion: validates against a problem's declared skills, updates
the per-topic rolling window, and answers the dashboard's overview query."""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from sqlmodel import Session, select

from app.engine.models.attempt import Attempt
from app.models.skill import Skill
from app.engine.models.skill_state import SkillState
from app.engine.schemas import (
    AttemptCreate,
    AttemptResult,
    SkillOverviewOut,
    SkillsOverviewResponse,
)
from app.services import attribution
from app.engine.accuracy import (
    estimated_accuracy,
    observed_accuracy,
    push_outcome,
    score_attempt,
)

logger = logging.getLogger(__name__)

# How long a newly-appended topic is flagged "recent" on the dashboard --
# long enough to notice it appear mid-session, short enough that the flag
# isn't still on from a run days ago.
RECENT_SKILL_WINDOW = timedelta(minutes=15)


class UnknownSkillError(ValueError):
    """An attempt declared expected_skills not present in the course taxonomy."""


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _get_or_create_skill_state(
    session: Session, student_id: str, course_id: str, skill_id: str
) -> SkillState:
    state = session.get(SkillState, (student_id, skill_id))
    if state is None:
        state = SkillState(student_id=student_id, course_id=course_id, skill_id=skill_id)
        session.add(state)
        session.flush()
    return state


def _existing_attempt(session: Session, student_id: str, problem_id: str) -> Attempt | None:
    return session.exec(
        select(Attempt).where(
            Attempt.student_id == student_id, Attempt.problem_id == problem_id
        )
    ).first()


def _resolve_skills(session: Session, payload: AttemptCreate) -> list[str]:
    """Which skills this attempt exercised, primary first.

    When the problem was generated by us, its ProblemSkill rows are the
    source of truth and the client's expected_skills is only a hint we
    cross-check -- a client cannot attribute an attempt to a skill it names.
    Problems with no row (legacy, or externally authored) fall back to the
    client's list, and that fallback is logged rather than silent.
    """
    server_skills = attribution.get_problem_skills(session, payload.problem_id)
    if not server_skills:
        logger.info(
            "problem %s has no problem_skills row; trusting client expected_skills %s",
            payload.problem_id,
            payload.expected_skills,
        )
        return payload.expected_skills

    if set(server_skills) != set(payload.expected_skills):
        logger.warning(
            "problem %s: overriding client expected_skills %s with server-side %s",
            payload.problem_id,
            payload.expected_skills,
            server_skills,
        )
    return server_skills


def record_attempt(
    session: Session,
    course_id: str,
    payload: AttemptCreate,
    now: datetime | None = None,
) -> AttemptResult:
    """`now` defaults to the wall clock; only the simulator passes one, to
    advance a virtual timestamp so staleness has something to measure."""
    now = now or _utcnow()
    # One problem, one attempt. The whiteboard posts on every "mark", so
    # repeats are expected traffic -- they are answered with the original
    # attempt rather than counted again.
    existing = _existing_attempt(session, payload.student_id, payload.problem_id)
    if existing is not None:
        logger.info(
            "attempt for problem %s by %s already recorded; returning it unchanged",
            payload.problem_id,
            payload.student_id,
        )
        return AttemptResult(
            attempt_id=existing.id,
            updated_skills={
                skill_id: estimated_accuracy(state.recent_outcomes)
                for skill_id in existing.expected_skills
                if (state := session.get(SkillState, (payload.student_id, skill_id)))
            },
        )

    expected_skills = _resolve_skills(session, payload)
    if not expected_skills:
        raise UnknownSkillError("attempt declared no skills")

    skills = session.exec(
        select(Skill).where(Skill.course_id == course_id, Skill.id.in_(expected_skills))
    ).all()
    missing = set(expected_skills) - {s.id for s in skills}
    if missing:
        raise UnknownSkillError(
            f"expected_skills not found in course '{course_id}': {sorted(missing)}"
        )

    score = score_attempt(
        correct=payload.correct, hints_used=payload.hints_used, partial=payload.partial
    )

    # Credit goes to the primary skill only -- the topic the question was
    # written for. One outcome cannot say which of four skills a wrong
    # answer failed at, and pushing the same score into all of them blurred
    # every topic on the problem while inflating the attempt counts that
    # confidence is built from. The rest stay on the ledger as attribution.
    primary = expected_skills[0]
    state = _get_or_create_skill_state(session, payload.student_id, course_id, primary)
    state.recent_outcomes = push_outcome(state.recent_outcomes, score)
    state.attempts += 1
    if payload.hints_used > 0:
        state.hints_used += 1
    state.last_seen = now
    session.add(state)

    attempt = Attempt(
        student_id=payload.student_id,
        course_id=course_id,
        session_id=payload.session_id,
        problem_id=payload.problem_id,
        expected_skills=expected_skills,
        difficulty=payload.difficulty,
        correct=payload.correct,
        partial=payload.partial,
        hints_used=payload.hints_used,
        error_tag=payload.error_tag,
        created_at=now,
    )
    session.add(attempt)
    session.commit()

    return AttemptResult(
        attempt_id=attempt.id,
        updated_skills={primary: estimated_accuracy(state.recent_outcomes)},
    )


def get_skills_overview(
    session: Session, course_id: str, student_id: str
) -> SkillsOverviewResponse:
    """Every topic in the course with this student's attempt history.

    Dashboard-only: the product surface never asks "what does this student
    know", because it never shows the student a per-topic readout.
    """
    skills = session.exec(select(Skill).where(Skill.course_id == course_id)).all()
    states = session.exec(
        select(SkillState).where(
            SkillState.student_id == student_id,
            SkillState.skill_id.in_([s.id for s in skills]),
        )
    ).all()
    state_by_id = {state.skill_id: state for state in states}
    now = _utcnow()

    out: list[SkillOverviewOut] = []
    for skill in skills:
        state = state_by_id.get(skill.id)
        outcomes = state.recent_outcomes if state else []
        created_at = skill.created_at
        if created_at.tzinfo is None:
            created_at = created_at.replace(tzinfo=timezone.utc)

        out.append(
            SkillOverviewOut(
                skill_id=skill.id,
                skill_name=skill.name,
                description=skill.description,
                difficulty_band=skill.difficulty_band,
                keywords=list(skill.keywords),
                question_forms=list(skill.question_forms),
                origin=skill.origin,
                created_at=created_at,
                is_recent=(now - created_at) <= RECENT_SKILL_WINDOW,
                observed=observed_accuracy(outcomes),
                estimate=estimated_accuracy(outcomes),
                attempts=state.attempts if state else 0,
                last_served=state.last_served if state else None,
            )
        )

    return SkillsOverviewResponse(student_id=student_id, course_id=course_id, skills=out)
